### ISSUE TITLE
Wizard needs to support all question types

### ISSUE THREAD

**Issue by Andersos** [DirektoratetForByggkvalitet/losen#21]
Complete list of all question types:
- [x] https://github.com/netliferesearch/dibk-wizard-framework/issues/22 Text block
- [x] https://github.com/netliferesearch/dibk-wizard-framework/issues/34 Text input
- [x] https://github.com/netliferesearch/dibk-wizard-framework/issues/35 Multi text input
- [x] https://github.com/netliferesearch/dibk-wizard-framework/issues/33 Multiple choice with multiple valid answer (checkboxes)
- [x] https://github.com/netliferesearch/dibk-wizard-framework/issues/32 Images
- [x] ~~https://github.com/netliferesearch/dibk-wizard-framework/issues/1 Multiple choice with only one valid answer (Radio buttons)~~
- [x] ~~https://github.com/netliferesearch/dibk-wizard-framework/issues/5 Drop-down question~~
- [x] ~~https://github.com/netliferesearch/dibk-wizard-framework/issues/4 Numbers~~

### Optional: Not part of requierments
- [ ] Question with date as answer
