### ISSUE TITLE
The framework needs to support images in questions, answers and in the helptext

### ISSUE THREAD

**Issue by Andersos** [DirektoratetForByggkvalitet/losen#23]
One of the requirements is that the framework needs to support images many places.

- [x] https://github.com/netliferesearch/dibk-wizard-framework/issues/30 Images in question
- [x] https://github.com/netliferesearch/dibk-wizard-framework/issues/31 Images in suggested answer
- [x] https://github.com/netliferesearch/dibk-wizard-framework/issues/32 Images between text block (tilleggsinformasjon)
